import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>baldhalla</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          welcome to <a href="https://baldhalla.com">baldhalla!</a>
        </h1>

        <p className={styles.description}>
         contribute to
          <code className={styles.code}><a href="https://github.com/omakasemoney/baldhalla">baldhalla!</a></code>
        </p>

        <div className={styles.grid}>
          being bald is okay
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/omakasemoney/baldhalla"
          target="_blank"
          rel="noopener noreferrer"
        >
          made by baldies
        </a>
      </footer>
    </div>
  )
}
